const Message = {
  KAPIError: 'Something went wrong.',
  KRequiredFiledsEmpty: 'Please fill all the required details',
  KCredentialEmpty: 'Mobile number and password should not be empty',
  KMobileEmpty: 'Mobile number should not be empty',
  KMobileInvalid: 'Enter valid Mobile Number',
  KInvalidMobile: 'Invalid mobile number',
  KOTPEmpty: 'OTP should not be empty',
  KOTPInvalid: 'Invalid OTP',
  KAgreeTermsCondition: 'Please accept the terms & conditions',
  KNameEmpty: 'Name should not be empty',
  KImageSize: 'Select Maximum 20MB File size',
  KSpecialCharError: 'Only alphabets are allow in name field',
  KNumberError: 'Only alphabets are allow in name field',
  KProfileEmpty: 'Profile should not be empty',
  KFirstNameEmpty: 'First name should not be empty',
  KLastNameEmpty: 'Last name should not be empty',
  KEmailEmpty: 'Email should not be empty',
  KEmailInvalid: 'Invalid email address',
  KDateOfBirthEmpty: 'Birth Date should not be empty',
  KVehicleMakeEmpty: 'Vehicle Make should not be empty',
  KModelEmpty: 'Model should not be empty',
  KVehicleNumberEmpty: 'Vehicle Number should not be empty',
  KDogCapacityEmpty: 'Dog Capacity should not be empty',
  KDrivingLicenseNoEmpty: 'Driving License Number should not be empty',
  KLicenseExpiryDateEmpty: 'License Expiry Date should not be empty',
  KLicensePlateEmpty: 'License Plate should not be empty',
  KInsuranceNumberEmpty: 'Insurance Number should not be empty',
  KVehicleRegistrationEmpty: 'Insurance Number should not be empty',
  KLicenseFrontImageEmpty: 'License Front Image should not be empty',
  KLicenseBackImageEmpty: 'License Back Image should not be empty',
  KLicenseAdsImageEmpty: 'License Ads Image should not be empty',
  KCheckInternetConnection: 'Please check internet connection.',
  KDogNameEmpty: 'Dog name should not be empty',
  KDogWeightEmpty: 'Dog weight should not be empty',
  KUploadImageEmpty: 'Please upload Image',
  KUploadDiscription: 'Please add Description',
  KCheckbox: 'Please Agree Conditions',
  KDogBreedEmpty: 'Dog breed should not be empty',
  KDogCarrirEmpty: 'Dog Carrier should not be empty',
  KHolderNameEmpty: 'Card Holder Name should not be empty',
  KCardNoEmpty: 'Card Number should not be empty',
  KEnterValidCardNo: 'Please Enter Valid Card Number',
  KExpDateEmpty: 'Card Expirey Date should not be empty',
  KCvvEmpty: 'Card CVV Number should not be empty',
  KEnterValidCvv: 'Please enter valid 3 digit cvv',
  KCardAndCvv: 'please check your card no. and cvv',
  KFeedback: 'please enter your feedback',
  KCancelTripReason: 'please enter your reason',
  KRating: 'please give rating ',
  KDiscriptionEmpty: 'please enter description',
  KInvalidFormate: 'Format not supported',
  KPINEmpty: 'PIN should not be empty',
  KPINInvalid: 'Invalid PIN',

  emails: 'Email is Not Correct',
  vmo: 'please Enter Indian Number Only',
  yourName: 'please enter yourName',
  commnet: 'please enter Comment',

  amount: 'please enter payableAmount',
  mortgageDetails: 'please select mortgageDetails',

  firstName: 'please enter firstName',
  lastName: 'please enter lastName',
  businessName: 'please enter businessName',
  address: 'please enter address',
  city: 'please enter cityName',
  state: 'please enter stateName',
  zipped: 'please enter PinCode',
  country: 'please enter countryName',
  taluka: 'please enter talukaName',
  district: 'please enter districtName',
  landmark: 'please enter landmark',
  panNumber: 'please enter panNumber',
  pancNumber: 'please check panNumber',
  gstNumber: 'please enter gstNumber',
  gstcNumber: 'please check gstNumber',
  businessLogo: 'please upload businessLogo',

  email: 'please enter email',
  mobileNumber: 'please enter mobileNumber',
  vmobileNumber: 'please enter valid mobileNumber',
  vatrmobileNumber: 'please enter valid AlternetNumber',
  dob: 'please enter DOB',
  image: 'Please upload image',

  area: 'please enter area',

  occupationType: 'please select occupationType',
  companyName: 'please enter companyName',
  income: 'please enter income',
  employeeId: 'please enter employeeId',
  businessEmail: 'please enter businessEmail',

  relation: 'please enter relation',

  selectdoc: 'please select atleast one document',
  aadahrNumber: 'please enter aadharNumber',
  aadahrvNumber: 'please enter valid aadharNumber',
  aadharFront: 'please upload aadhar FrontImage',
  aadharBack: 'please upload aadhar BackImage',
  pancard: 'please upload pancardImage',
  pancards: 'please enter pancardNumber',
  drivingLicense: 'please upload drivingLicenceImage',
  drivingLicenseNumber: 'please enter drivingLicenceNumber',
  drivingvLicenseNumber: 'please enter valid drivingLicenceNumber',
  panNumbers: 'please enter valid pancardNumber',

  accountHolderName: 'please enter accountHolderName',
  checkNumber: 'please enter checkNumber',
  checkNumbers: 'please enter valid checkNumber',
  bankName: 'please enter bankName',
  accountNumber: 'please enter accountNumber',
  accountNumbers: 'please enter valid accountNumber',
  netValue: 'please enter netValue',
  checkImage: 'please upload chequeImage',

  MatelType: 'please select MatelType',
  JewelryType: 'please select JewelryType',
  purity: 'please enter Purity',
  netWeight: 'please enter NetWeight',
  valuation: 'please enter Valuation',
  JewelryImage: 'please upload JewelryImage',

  applianceName: 'please select applianceName',
  brand: 'please select brand',
  model: 'please select model',
  color: 'please select color',
  variant: 'please select variant',
  price: 'please enter price',
  serialNumber: 'please enter serialNumber',
  productImage: 'please upload productImage',
  invoiceImage: 'please upload invoiceImage',

  processingFees: 'please enter processingFees',
  downPaymentAmount: 'please enter downPaymentAmount',
  downPaymentAmountp: 'downpaymentamount not more than productPrice',
  rate: 'please enter rate',
  duration: 'please enter duration',
  emiType: 'please select emiType',
  emiDate: 'please select emiDate',
};

export default Message;
